spring:
  application:
    name: categorization-service
  datasource:
    url: jdbc:postgresql://localhost:1298/postgres
    username: postgres
    password: Kowsidhina0609!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: categorization-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: com.chameleon.categorization.dto.TransactionEvent
        spring.json.trusted.packages: "*"
server:
  port: 8082

chameleon:
  knn:
    k: 5