server:
  port: 8086
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: notification-service
          uri: http://localhost:8085
          predicates: [/api/notifications/**]
        - id: credit-history-service
          uri: http://localhost:8084
          predicates: [/api/credit-history/**]
        - id: card-engine-service
          uri: http://localhost:8080
          predicates: [/api/cards/**]
        - id: categorization-service
          uri: http://localhost:8082
          predicates: [/api/categories/**]
        - id: reward-service
          uri: http://localhost:8083
          predicates: [/api/rewards/**]
        - id: transaction-service
          uri: http://localhost:8081
          predicates: [/api/transactions/**]

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: http://localhost:3000
            allowedMethods: GET, POST, PATCH, PUT, DELETE, OPTIONS
            allowedHeaders: "*"
            allowCredentials: true