spring:
  application:
    name: credit-history-service
  datasource:
    url: jdbc:postgresql://localhost:1298/postgres
    username: postgres
    password: Kowsidhina0609!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8084