server:
  port: 8084
spring:
  application:
    name: credit-history-service
  datasource:
    url: jdbc:postgresql://localhost:1298/postgres
    username: postgres
    password: Kowsidhina0609!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: credit-history-service
#      auto-offset-reset: earliest
#      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframwork.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
logging:
  level:
    com.chameleon: DEBUG